csk/urls.py
from django.urls import path
from csk.views import *
app_name='cskteam'

urlpatterns=[
    path('msd/',msd,name='msd')
]

rcb/urls.py
from django.urls import path
from rcb.views import *
app_name='rcbteam'

urlpatterns=[
    path('king/',king,name='king'),
]

work2/urls.py
from django.contrib import admin
from django.urls import path,include
import csk,rcb

urlpatterns = [
    path('admin/', admin.site.urls),
    path('csk/',include('csk.urls')),
    path('rcb/',include('rcb.urls')),
]

csk/models.py
from django.db import models

# Create your models here.

rcb/models.py
from django.db import models

# Create your models here.

csk/views.py
from django.shortcuts import render

# Create your views here.
def msd(request):
    return render(request,'msd.html')
def king(request):
    return render(request,'rcb.html')

rcb/views.py
from django.shortcuts import render

# Create your views here.
def king(request):
    return render(request,'king.html')

templates/king.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>thanks ms sir </h1>
        <a href="{% url 'cskteam:msd'%}"> msd</a>
       
    </center>
</body>
</html>

templates/msd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>King is one of the best cricet</h1>
        <h1><a href="{% url 'rcbteam:king' %}">king </a></h1>
    </center>
</body>
</html>